name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: List files to find gradlew
        run: ls -R  # Bu komut tüm dosyaları ve klasörleri listeleyecektir

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build APK
        run: echo "Gradlew dosyasını yukarıdaki listeden bulup yolunu düzelteceğiz."
